# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Seeking-Shelter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Seeking-Shelter
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'MaterialComponents'
  
  target 'Seeking-ShelterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Seeking-ShelterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
